### PR TITLE
Add safe replace of missing entries in CSV sheets, add init poetry config with dependencies

### PR DESCRIPTION
**Pull request by oshapio**
1. Running __main__.py locally using a CSV raised errors when the `WORKSHEET` entry wasn't found. Dirty solution was to ignore such entries.
2. Add init poetry config with dependencies: this makes it easy to install the repo on a fresh virtual env with matching dependencies.

### CODE REVIEW

**Comment by AlexanderRubinstein** [comment]
@oshapio Could you please specify how you tested that code works with poetry?

**Comment by oshapio** [comment]
Sure! 

Commands:
```bash
$ git clone https://github.com/AlexanderRubinstein/STAI-tuned STAI-tuned-testing
$ git checkout arnas/safe-replace
$ poetry install
$ poetry shell
$ emulate bash -c '. /home/nas/.cache/pypoetry/virtualenvs/stuned-K8NDGnaH-py3.10/bin/activate'
$ python -m stuned.run_from_csv
```
Output:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/nas/Documents/STAI-tuned-testing/src/stuned/run_from_csv/__init__.py", line 1, in <module>
    from .__main__ import (
  File "/home/nas/Documents/STAI-tuned-testing/src/stuned/run_from_csv/__main__.py", line 13, in <module>
    from utility.utils import (
  File "/home/nas/Documents/STAI-tuned-testing/src/stuned/utility/utils.py", line 39, in <module>
    DEFAULT_ENV_NAME = os.environ["DEFAULT_ENV"]
  File "/usr/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'DEFAULT_ENV'
```

**Comment by AlexanderRubinstein** [comment]
> Sure!
> 
> Commands:
> 
> ```shell
> $ git clone https://github.com/AlexanderRubinstein/STAI-tuned STAI-tuned-testing
> $ git checkout arnas/safe-replace
> $ poetry install
> $ poetry shell
> $ emulate bash -c '. /home/nas/.cache/pypoetry/virtualenvs/stuned-K8NDGnaH-py3.10/bin/activate'
> $ python -m stuned.run_from_csv
> ```
> 
> Output:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/home/nas/Documents/STAI-tuned-testing/src/stuned/run_from_csv/__init__.py", line 1, in <module>
>     from .__main__ import (
>   File "/home/nas/Documents/STAI-tuned-testing/src/stuned/run_from_csv/__main__.py", line 13, in <module>
>     from utility.utils import (
>   File "/home/nas/Documents/STAI-tuned-testing/src/stuned/utility/utils.py", line 39, in <module>
>     DEFAULT_ENV_NAME = os.environ["DEFAULT_ENV"]
>   File "/usr/lib/python3.10/os.py", line 680, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'DEFAULT_ENV'
> ```
> 
> (Need to set the variables for it to run of course)

Sorry for the confusion, I meant: how do you test that after your commits everything works as intended?

**Comment by AlexanderRubinstein** [comment]
Hope that we can merge job monitor in a new dedicated pr

**Pull request closed without merging**
